### ISSUE TITLE
EVM Explorer(anvil ) data is incorrect

### ISSUE THREAD

**Issue by aisinoluhua** [FindoraNetwork/findora-exporter#8]
anvil EVM Explorer can query the main data
Query address available for testing: 0xA9a6E17a05c71BFe168CA972368F4b98774BF6C3
You can see that anvil has two pieces of data, the block 1837982 is the data of mainnet.

**Comment by tommady** [comment]
Hi, @aisinoluhua sorry for responding so late.

And sorry again, could you describe the issue more clearly?
I couldn't understand what you were trying to say.

Thank you.

**Comment by tommady** [comment]
close because no responding after a month
